"""Mousepad database — curated real-world mousepads with friction & size data."""

MOUSEPADS = [
    # ===== Speed pads (low friction, fast glide) =====
    {
        "id": "artisan-raiden",
        "name": "Artisan Raiden",
        "brand": "Artisan",
        "surface": "speed",
        "material": "cloth",
        "static_friction": 1.2,
        "dynamic_friction": 1.0,
        "stopping_power": 1.5,
        "speed_rating": 9.5,
        "sizes": ["M", "L", "XL"],
        "thickness": "mid",
        "price_cny": 399,
        "image": "https://www.artisan-jp.com/img/raiden/raiden_fx_xs_01.jpg",
        "desc": "超细编织布面，极低摩擦，适合高 eDPI 玩家的高速滑行需求。",
        "detail_desc": "Artisan Raiden 采用超细聚酯纤维编织表面（Micro-weave Polyester），拥有 Artisan 全系最低的初始摩擦与动态摩擦。表面极为平滑，鼠标移动如履薄冰，无颗粒感。兼容 XSoft/Soft/Mid 三种硬度基底，其中 XSoft 提供额外的下压制动能力。尺寸覆盖 M（31×24cm）至 XL（49×42cm），日本手工制造。适合 CS2、Valorant 等高要求 FPS 中偏爱极速滑行的高灵敏度玩家。",
        "desc_source": "来源：Artisan 官方产品页（artisan-jp.com）",
        "dimensions": {"glide": 9, "control": 3, "durability": 7, "comfort": 7, "compatibility": 7, "value": 5},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Artisan+Raiden+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Artisan+Raiden+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Artisan+Raiden+FX+mousepad",
            "official": "https://www.artisan-jp.com/fx_raiden.html"
        }
    },
    {
        "id": "artisan-shidenkai",
        "name": "Artisan Shidenkai",
        "brand": "Artisan",
        "surface": "speed",
        "material": "glass-coated",
        "static_friction": 0.8,
        "dynamic_friction": 0.6,
        "stopping_power": 1.0,
        "speed_rating": 10.0,
        "sizes": ["M", "L", "XL"],
        "thickness": "mid",
        "price_cny": 459,
        "image": "https://www.artisan-jp.com/img/shidenkai/shidenkai_fx_xs_01.jpg",
        "desc": "玻璃涂层表面，极致顺滑，业界最快之一，适合追求极限速度的玩家。",
        "detail_desc": "Artisan Shidenkai 采用布面+玻璃微珠涂层双层结构，表面嵌入微米级玻璃珠粒，摩擦系数为 Artisan 全系最低。滑动手感与硬质玻璃垫接近，但保留布垫的柔软下压反馈。已知缺陷为涂层寿命有限（约 6-12 个月高频使用后玻璃珠脱落、表面变涩）。兼容 Mid/XSoft 硬度，尺寸 M-XL。适合对速度有极致追求、可接受定期更换的用户。",
        "desc_source": "来源：Artisan 官方产品页（artisan-jp.com）",
        "dimensions": {"glide": 10, "control": 2, "durability": 3, "comfort": 5, "compatibility": 6, "value": 4},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Artisan+Shidenkai+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Artisan+Shidenkai+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Artisan+Shidenkai+FX+mousepad",
            "official": "https://www.artisan-jp.com/fx_shidenkai.html"
        }
    },
    {
        "id": "glorious-ice",
        "name": "Glorious Ice",
        "brand": "Glorious",
        "surface": "speed",
        "material": "hybrid",
        "static_friction": 1.5,
        "dynamic_friction": 1.2,
        "stopping_power": 2.0,
        "speed_rating": 8.5,
        "sizes": ["M", "L", "XL"],
        "thickness": "thin",
        "price_cny": 199,
        "image": None,
        "desc": "混合材质冰感表面，性价比高的速度垫，适合预算有限的速度党。",
        "detail_desc": "Glorious Ice 采用混合材质编织表面（Hybrid Cloth），表面经过特殊处理呈现冰感光滑触感，初始滑动阻力极小。基底为天然橡胶防滑纹路，厚度约 2mm（薄款），边缘无包边缝合。提供中型到桌面级多种尺寸，价格亲民（$20-40 USD）。定位为预算型速度垫，适合从控制垫转向速度垫的入门用户，表面耐用性中等。",
        "desc_source": "来源：Glorious 官方产品页（gloriousgaming.com）",
        "dimensions": {"glide": 8, "control": 3, "durability": 6, "comfort": 7, "compatibility": 7, "value": 7},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Glorious+Ice+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Glorious+Ice+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Glorious+Ice+mousepad",
            "official": "https://www.gloriousgaming.com/products/glorious-ice"
        }
    },
    {
        "id": "razer-strider",
        "name": "Razer Strider",
        "brand": "Razer",
        "surface": "speed",
        "material": "hybrid",
        "static_friction": 1.8,
        "dynamic_friction": 1.4,
        "stopping_power": 2.5,
        "speed_rating": 8.0,
        "sizes": ["L", "XXL"],
        "thickness": "thin",
        "price_cny": 299,
        "image": None,
        "desc": "混合编织表面，防水耐磨，兼顾速度与微操，桌垫版覆盖全桌面。",
        "detail_desc": "Razer Strider 采用混合编织表面（Hybrid Cloth），融合聚酯纤维与防水涂层，具备 IPX4 级防水能力，汗渍与水渍不易渗透。表面纹理介于布垫与硬垫之间，提供清晰的滑动反馈与中等制动。边缘使用高密度缝合线包边，抗起毛。最突出的规格为 XXL 桌垫版（940×410mm），覆盖全桌面。底部为蜂巢纹防滑橡胶。",
        "desc_source": "来源：Razer 官方产品页（razer.com）",
        "dimensions": {"glide": 8, "control": 4, "durability": 7, "comfort": 7, "compatibility": 8, "value": 7},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Razer+Strider+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Razer+Strider+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Razer+Strider+mousepad",
            "official": "https://www.razer.com/gaming-mouse-mats/razer-strider"
        }
    },
    {
        "id": "skypad-glass",
        "name": "SkyPAD 3.0 Glass",
        "brand": "SkyPAD",
        "surface": "speed",
        "material": "glass",
        "static_friction": 0.5,
        "dynamic_friction": 0.4,
        "stopping_power": 0.5,
        "speed_rating": 10.0,
        "sizes": ["L", "XL"],
        "thickness": "thin",
        "price_cny": 699,
        "image": None,
        "desc": "全钢化玻璃表面，零磨损极速滑行，适合追求极致速度且不介意硬垫的用户。",
        "detail_desc": "SkyPAD 3.0 采用全钢化玻璃材质（Tempered Glass），CNC 数控切割边缘，表面经过微蚀刻处理提供极低但非零的摩擦。完全不磨损——鼠标脚贴是唯一的消耗品。硬质表面无下压形变，制动全靠玩家手部控制。尺寸为 L（350×400mm）与 XL（400×500mm），厚度约 3mm。需搭配 PTFE 或玻璃脚贴使用（陶瓷脚贴可能划伤表面）。噪音较大，适合追求绝对一致性滑动手感的硬核玩家。",
        "desc_source": "来源：SkyPAD 官方产品页（skypad-gaming.com）",
        "dimensions": {"glide": 10, "control": 1, "durability": 10, "comfort": 4, "compatibility": 6, "value": 5},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=SkyPAD+3.0+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=SkyPAD+3.0+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=SkyPAD+3.0+glass+mousepad",
            "official": "https://skypad-gaming.com/products/skypad-3-0"
        }
    },
    {
        "id": "logitech-g440",
        "name": "Logitech G440",
        "brand": "Logitech",
        "surface": "speed",
        "material": "hard",
        "static_friction": 1.5,
        "dynamic_friction": 1.1,
        "stopping_power": 1.8,
        "speed_rating": 8.0,
        "sizes": ["M"],
        "thickness": "thin",
        "price_cny": 149,
        "image": None,
        "desc": "硬质聚合物表面，低摩擦高响应，入门级硬垫首选。",
        "detail_desc": "Logitech G440 采用硬质聚合物表面（Hard Polymer），表面纹理均匀细腻，摩擦系数低且一致性好。单尺寸 340×280mm（中号），厚度约 3mm。底部为天然橡胶防滑基底。作为入门级硬垫，价格亲民，适合首次尝试硬质鼠标垫的用户。缺点是表面长期使用后会磨光（高频率使用约 6 个月出现滑动一致性下降），且尺寸偏小对低灵敏度玩家不够友好。",
        "desc_source": "来源：Logitech 官方产品页（logitech.com）",
        "dimensions": {"glide": 8, "control": 3, "durability": 5, "comfort": 5, "compatibility": 7, "value": 8},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Logitech+G440+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Logitech+G440+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Logitech+G440+mousepad",
            "official": "https://www.logitech.com/en-us/products/gaming/g440-hard-gaming-mouse-pad.html"
        }
    },

    # ===== Balanced pads =====
    {
        "id": "artisan-hien",
        "name": "Artisan Hien",
        "brand": "Artisan",
        "surface": "balanced",
        "material": "cloth",
        "static_friction": 3.0,
        "dynamic_friction": 2.5,
        "stopping_power": 3.5,
        "speed_rating": 7.0,
        "sizes": ["M", "L", "XL"],
        "thickness": "mid",
        "price_cny": 399,
        "image": "https://www.artisan-jp.com/img/hien/hien_fx_xs_01.jpg",
        "desc": "粗面编织，独特的 X/Y 轴差异化摩擦，平衡速度与控制，Artisan 最畅销型号。",
        "detail_desc": "Artisan Hien 采用粗面聚酯纤维编织（Coarse-weave Polyester），是 Artisan 最畅销型号。标志性特征为 X/Y 轴差异化摩擦——水平方向（X 轴）滑动速度明显快于垂直方向（Y 轴），由编织纹理方向决定。表面颗粒感明显，为玩家提供清晰的滑动触觉反馈。耐用性极佳，编织纹理不易磨损。兼容 Mid/Soft/XSoft 三种硬度，尺寸 M-XL。适合追求速度+反馈感、不拘泥于纯平滑表面的 FPS 玩家。",
        "desc_source": "来源：Artisan 官方产品页（artisan-jp.com）",
        "dimensions": {"glide": 7, "control": 5, "durability": 9, "comfort": 6, "compatibility": 8, "value": 6},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Artisan+Hien+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Artisan+Hien+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Artisan+Hien+FX+mousepad",
            "official": "https://www.artisan-jp.com/fx_hien.html"
        }
    },
    {
        "id": "artisan-hayate-otsu",
        "name": "Artisan Hayate Otsu",
        "brand": "Artisan",
        "surface": "balanced",
        "material": "cloth",
        "static_friction": 3.5,
        "dynamic_friction": 2.8,
        "stopping_power": 4.0,
        "speed_rating": 6.5,
        "sizes": ["M", "L", "XL"],
        "thickness": "mid",
        "price_cny": 399,
        "image": "https://www.artisan-jp.com/img/hayate_otsu/hayate_otsu_fx_xs_01.jpg",
        "desc": "介于 Hien 和 Zero 之间的万金油，微纹理提供清晰启停反馈。",
        "detail_desc": "Artisan Hayate Otsu 定位为 Hien（速度）与 Zero（控制）之间的平衡型号。表面采用微纹理编织（Micro-textured Polyester），比 Hien 更细腻平滑，但保留足够的颗粒感以提供清晰的启动/制动反馈。滑动速度略慢于 Hien、快于 Zero，是 Artisan 全系中适用面最广的万金油。兼容 Mid/Soft/XSoft 三种硬度基底，尺寸 M-XL。适合不确定自己偏好、或需要在速度与控制之间取得最佳折中的玩家。",
        "desc_source": "来源：Artisan 官方产品页（artisan-jp.com）",
        "dimensions": {"glide": 7, "control": 6, "durability": 7, "comfort": 8, "compatibility": 8, "value": 5},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Artisan+Hayate+Otsu+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Artisan+Hayate+Otsu+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Artisan+Hayate+Otsu+FX+mousepad",
            "official": "https://www.artisan-jp.com/fx_hayate_otsu.html"
        }
    },
    {
        "id": "lgg-saturn",
        "name": "LGG Saturn",
        "brand": "Lethal Gaming Gear",
        "surface": "balanced",
        "material": "cloth",
        "static_friction": 4.0,
        "dynamic_friction": 3.0,
        "stopping_power": 4.5,
        "speed_rating": 5.5,
        "sizes": ["L", "XL", "XXL"],
        "thickness": "standard",
        "price_cny": 249,
        "image": None,
        "desc": "平滑布面，控制力出色，Artisan Zero 的平替之选，性价比极高。",
        "detail_desc": "LGG Saturn 采用平滑编织布面（Smooth Cloth），表面触感柔软细腻，滑动速度定位为中等偏控制。基底为类 Poron 聚氨酯泡棉（类似 Artisan Soft 硬度），提供均匀的下压缓冲。尺寸覆盖 L（490×410mm）到 XXL（1000×500mm），边缘采用低于表面的缝合包边工艺不硌手。被社区广泛视为 Artisan Zero 最具性价比的替代品，价格约为 Zero 的 60%，表面耐用性与防潮性优于 Zero。",
        "desc_source": "来源：Lethal Gaming Gear 官方产品页（lethal.gg）",
        "dimensions": {"glide": 5, "control": 7, "durability": 8, "comfort": 8, "compatibility": 8, "value": 8},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=LGG+Saturn+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=LGG+Saturn+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=LGG+Saturn+mousepad",
            "official": "https://lethal.gg/products/lgg-saturn"
        }
    },
    {
        "id": "aqua-control-plus",
        "name": "Aqua Control+",
        "brand": "X-raypad",
        "surface": "balanced",
        "material": "cloth",
        "static_friction": 3.8,
        "dynamic_friction": 3.2,
        "stopping_power": 4.2,
        "speed_rating": 6.0,
        "sizes": ["L", "XL", "XXL"],
        "thickness": "standard",
        "price_cny": 179,
        "image": None,
        "desc": "粗面布垫，受潮不黏滞，耐用性极强，国货性价比之选。",
        "detail_desc": "X-raypad Aqua Control+ 采用粗面编织布面（Rough Textured Cloth），表面有不规则颗粒纹理提供中等的滑动速度与控制力。核心优势为出色的防潮性能——高湿度环境下表面不会变黏滞，这对南方用户尤为重要。ROB 版（ROB Edition）与普通版表面涂层不同，ROB 更偏控制。尺寸覆盖 L 至 XXL 及多种定制图案，价格极为亲民。底部为蜂窝纹橡胶防滑，边缘可选包边。是国货中口碑最好的均衡型鼠标垫之一。",
        "desc_source": "来源：X-raypad 官方产品页（x-raypad.com）",
        "dimensions": {"glide": 6, "control": 6, "durability": 8, "comfort": 6, "compatibility": 8, "value": 9},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Aqua+Control%2B+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Aqua+Control%2B+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Aqua+Control%2B+mousepad",
            "official": "https://www.x-raypad.com/aqua-control-plus"
        }
    },
    {
        "id": "steelseries-qck-heavy",
        "name": "SteelSeries QcK Heavy",
        "brand": "SteelSeries",
        "surface": "balanced",
        "material": "cloth",
        "static_friction": 4.5,
        "dynamic_friction": 3.5,
        "stopping_power": 5.0,
        "speed_rating": 4.5,
        "sizes": ["M", "L", "XXL"],
        "thickness": "thick",
        "price_cny": 199,
        "image": None,
        "desc": "经典加厚布垫，十余年职业赛场验证，微操稳定，入门到职业通用。",
        "detail_desc": "SteelSeries QcK Heavy 是电竞史上最具传奇色彩的鼠标垫之一。表面为微编织布面（Micro-woven Cloth），提供中等偏控制的滑动手感。最大特征是 6mm 加厚天然橡胶基底——远超市面常见的 3-4mm，厚底可以有效吸收桌面不平整，提供均匀一致的表面张力。十余年来被 CS 职业赛场广泛使用，从入门到职业通用。缺点是布面受潮后摩擦会增大，且边缘无包边长期使用可能起毛。尺寸覆盖 M 到 XXL。",
        "desc_source": "来源：SteelSeries 官方产品页（steelseries.com）",
        "dimensions": {"glide": 5, "control": 7, "durability": 6, "comfort": 9, "compatibility": 9, "value": 8},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=SteelSeries+QcK+Heavy+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=SteelSeries+QcK+Heavy+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=SteelSeries+QcK+Heavy+mousepad",
            "official": "https://steelseries.com/gaming-mousepads/qck-heavy"
        }
    },

    # ===== Control pads (high friction, maximum stopping power) =====
    {
        "id": "artisan-zero",
        "name": "Artisan Zero",
        "brand": "Artisan",
        "surface": "control",
        "material": "cloth",
        "static_friction": 5.5,
        "dynamic_friction": 4.0,
        "stopping_power": 6.0,
        "speed_rating": 3.5,
        "sizes": ["M", "L", "XL"],
        "thickness": "mid",
        "price_cny": 399,
        "image": "https://www.artisan-jp.com/img/zero/zero_fx_xs_01.jpg",
        "desc": "Artisan 控制垫标杆，绒面编织提供精准制动，低 eDPI FPS 玩家的终点站。",
        "detail_desc": "Artisan Zero 采用绒面聚酯纤维编织（Soft Polyester），是 Artisan 的控制垫标杆。表面触感柔软如绒布（Fluffy Texture），但滑动阻力为 Artisan 全系最高。在 XSoft 硬度下，下压鼠标可显著增加制动力——这一特性深受 CS2 职业选手青睐（急停定位时手指发力下压获得额外制动）。兼容 Mid/Soft/XSoft 三种硬度，尺寸 M-XL。缺点是表面易吸附毛发灰尘（因绒面静电），需定期清洁。是低 eDPI 战术 FPS 玩家的终点站级选择。",
        "desc_source": "来源：Artisan 官方产品页（artisan-jp.com）",
        "dimensions": {"glide": 4, "control": 8, "durability": 7, "comfort": 9, "compatibility": 8, "value": 5},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Artisan+Zero+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Artisan+Zero+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Artisan+Zero+FX+mousepad",
            "official": "https://www.artisan-jp.com/fx_zero.html"
        }
    },
    {
        "id": "zowie-gsr",
        "name": "ZOWIE G-SR",
        "brand": "ZOWIE",
        "surface": "rough",
        "material": "cloth",
        "static_friction": 6.0,
        "dynamic_friction": 4.5,
        "stopping_power": 7.0,
        "speed_rating": 2.5,
        "sizes": ["L"],
        "thickness": "standard",
        "price_cny": 229,
        "image": None,
        "desc": "高阻力布面，职业 FPS 选手经典之选，极强制动能力，受潮后阻力进一步增大。",
        "detail_desc": "ZOWIE G-SR 是 FPS 电竞史上影响力最大的控制垫之一。表面为高密度编织布面，初始静摩擦极高——这意味着鼠标从静止到启动需要更大的力道，但一旦进入滑动状态后动摩擦适中。3.5mm 标准厚度搭配天然橡胶基底，单一大尺寸 470×390mm。核心特点为极强的制动能力（Stopping Power），甩枪后鼠标可迅速静止，是低灵敏度 CS 职业选手的经典选择。最大的争议点为湿度敏感性——潮湿环境下布面摩擦显著增大、手感明显变涩。边缘无包边。",
        "desc_source": "来源：ZOWIE 官方产品页（zowie.benq.com）",
        "dimensions": {"glide": 2, "control": 9, "durability": 6, "comfort": 7, "compatibility": 7, "value": 7},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=ZOWIE+G-SR+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=ZOWIE+G-SR+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=ZOWIE+G-SR+mousepad",
            "official": "https://zowie.benq.com/en-us/mouse-pad/g-sr.html"
        }
    },
    {
        "id": "zowie-gsr-se",
        "name": "ZOWIE G-SR-SE",
        "brand": "ZOWIE",
        "surface": "control",
        "material": "cloth",
        "static_friction": 5.0,
        "dynamic_friction": 3.8,
        "stopping_power": 5.5,
        "speed_rating": 3.0,
        "sizes": ["L"],
        "thickness": "standard",
        "price_cny": 249,
        "image": None,
        "desc": "G-SR 的微调版，略低的初始摩擦，比 G-SR 更泛用但仍偏控制。",
        "detail_desc": "ZOWIE G-SR-SE（Special Edition）是 G-SR 的速度微调版本。表面采用与 G-SR 不同的编织密度和特殊涂层处理，初始静摩擦比 G-SR 低约 15-20%，启动更轻松但保留了大部分制动能力。尺寸与 G-SR 同为 470×390mm，3.5mm 厚度。SE 版的涂层在高频使用下会逐渐磨损（约 8-12 个月后滑动速度会变得接近普通 G-SR）。配色通常为红色/蓝色限定款。适合觉得 G-SR 太涩、但仍需要较强制动控制的玩家。",
        "desc_source": "来源：ZOWIE 官方产品页（zowie.benq.com）",
        "dimensions": {"glide": 3, "control": 8, "durability": 5, "comfort": 7, "compatibility": 7, "value": 6},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=ZOWIE+G-SR-SE+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=ZOWIE+G-SR-SE+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=ZOWIE+G-SR-SE+mousepad",
            "official": "https://zowie.benq.com/en-us/mouse-pad/g-sr-se.html"
        }
    },
    {
        "id": "lgg-jupiter",
        "name": "LGG Jupiter",
        "brand": "Lethal Gaming Gear",
        "surface": "rough",
        "material": "cloth",
        "static_friction": 6.5,
        "dynamic_friction": 5.0,
        "stopping_power": 7.5,
        "speed_rating": 2.0,
        "sizes": ["L", "XL", "XXL"],
        "thickness": "standard",
        "price_cny": 249,
        "image": None,
        "desc": "LGG 最慢垫，超高制动力，专为大范围甩枪和超低 eDPI 设计。",
        "detail_desc": "LGG Jupiter 是 Lethal Gaming Gear 产品线中摩擦最高的型号，定位为极致控制垫。表面采用高密度平滑布面，动态摩擦与静摩擦均极高，制动能力为 17 款数据库鼠标垫中最高等级。基底为软质聚氨酯泡棉，提供额外的下压制动力。尺寸覆盖 L（490×410mm）至 XXL（1000×500mm），边缘低于表面缝合不硌手。专为超低 eDPI（cm/360 > 50cm）、大范围甩枪（Wide Flick）场景设计。社区反馈其速度相当于 ZOWIE G-SR 受潮后的手感——但 Jupiter 的防潮性更好、摩擦力更稳定一致。",
        "desc_source": "来源：Lethal Gaming Gear 官方产品页（lethal.gg）",
        "dimensions": {"glide": 2, "control": 10, "durability": 8, "comfort": 8, "compatibility": 8, "value": 7},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=LGG+Jupiter+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=LGG+Jupiter+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=LGG+Jupiter+mousepad",
            "official": "https://lethal.gg/products/lgg-jupiter"
        }
    },
    {
        "id": "xraypad-equate",
        "name": "X-raypad Equate",
        "brand": "X-raypad",
        "surface": "rough",
        "material": "cloth",
        "static_friction": 6.0,
        "dynamic_friction": 4.8,
        "stopping_power": 6.5,
        "speed_rating": 2.5,
        "sizes": ["L", "XL"],
        "thickness": "standard",
        "price_cny": 159,
        "image": None,
        "desc": "控制型粗面垫，高性价比 G-SR 替代，耐潮不变黏。",
        "detail_desc": "X-raypad Equate 采用粗面控制型编织布面，定位为高性价比的控制垫。表面有明显颗粒纹理，提供高初始摩擦和强大的制动能力。与 ZOWIE G-SR 最大的差异在于防潮性能——Equate 在高湿度环境下不会像 G-SR 那样大幅变涩，南方玩家友好。尺寸覆盖 L（460×410mm）到 XL（900×400mm），底部为蜂窝纹防滑橡胶。价格约为 G-SR 的 60-70%，是国货中口碑最好的纯控制型鼠标垫之一。适合低灵敏度 FPS 玩家、寻找 G-SR 替代品的用户。",
        "desc_source": "来源：X-raypad 官方产品页（x-raypad.com）",
        "dimensions": {"glide": 2, "control": 9, "durability": 8, "comfort": 6, "compatibility": 8, "value": 9},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=X-raypad+Equate+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=X-raypad+Equate+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=X-raypad+Equate+mousepad",
            "official": "https://www.x-raypad.com/equate"
        }
    },
    {
        "id": "gamesense-radar",
        "name": "Gamesense Radar",
        "brand": "Gamesense",
        "surface": "control",
        "material": "cloth",
        "static_friction": 5.5,
        "dynamic_friction": 4.2,
        "stopping_power": 6.0,
        "speed_rating": 3.0,
        "sizes": ["L", "XL", "XXL"],
        "thickness": "standard",
        "price_cny": 229,
        "image": None,
        "desc": "平滑控制垫，表面质感接近 Zero，价格更亲民。",
        "detail_desc": "Gamesense Radar 采用平滑控制型布面（Smooth Control Cloth），表面触感与 Artisan Zero 高度相似——柔软绒面、中高摩擦。滑动速度略快于 Zero、慢于 LGG Saturn，定位为纯控制垫。基底为中等硬度橡胶，下压可增加额外制动力。尺寸覆盖 L 到 XXL 且有多种定制图案可选。价格比 Artisan Zero 低约 40%，社区常将其作为 Zero 的控制型平替推荐。边缘包边工艺良好，耐用性中上。",
        "desc_source": "来源：Gamesense 官方产品页（gamesense.gg）",
        "dimensions": {"glide": 3, "control": 8, "durability": 7, "comfort": 8, "compatibility": 8, "value": 7},
        "purchase_links": {
            "jd": "https://search.jd.com/Search?keyword=Gamesense+Radar+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "taobao": "https://s.taobao.com/search?q=Gamesense+Radar+%E9%BC%A0%E6%A0%87%E5%9E%AB",
            "amazon": "https://www.amazon.com/s?k=Gamesense+Radar+mousepad",
            "official": "https://gamesense.gg/products/radar"
        }
    },
]


# Individual games with verified Yaw values
# cm/360 = 360 / (DPI x Sens x Yaw) x 2.54
# Yaw = degrees of rotation per mouse count at sens=1.0
GAMES = {
    "cs2": {
        "name": "CS2",
        "category": "战术FPS",
        "yaw": 0.022,
        "bias": 0.0,
        "note": "m_yaw 默认 0.022",
    },
    "valorant": {
        "name": "Valorant",
        "category": "战术FPS",
        "yaw": 0.07,
        "bias": 0.0,
        "note": "Valorant 1.0 sens ≈ CS 0.314 sens",
    },
    "r6s": {
        "name": "彩虹六号:围攻",
        "category": "战术FPS",
        "yaw": 0.02,
        "bias": 0.0,
        "note": "默认腰射灵敏度乘数 0.02",
    },
    "apex": {
        "name": "Apex Legends",
        "category": "跟枪FPS",
        "yaw": 0.022,
        "bias": 0.0,
        "note": "Source 引擎，m_yaw = 0.022",
    },
    "ow2": {
        "name": "守望先锋2",
        "category": "跟枪FPS",
        "yaw": 0.0066,
        "bias": 0.0,
        "note": "OW 1.0 sens ≈ CS 3.33 sens",
    },
    "cod": {
        "name": "使命召唤",
        "category": "跟枪FPS",
        "yaw": 0.022,
        "bias": 0.0,
        "note": "COD 默认灵敏度乘数 0.022",
    },
    "fortnite": {
        "name": "Fortnite",
        "category": "跟枪FPS",
        "yaw": 0.0555,
        "bias": 0.0,
        "note": "Fortnite 1.0 ≈ CS 0.4 sens",
    },
    "quake": {
        "name": "Quake",
        "category": "竞技场FPS",
        "yaw": 0.022,
        "bias": 0.0,
        "note": "m_yaw = 0.022，高速竞技场风格",
    },
    "lol": {
        "name": "英雄联盟",
        "category": "MOBA",
        "yaw": 0.022,
        "bias": 0.0,
        "note": "MOBA 类游戏，高灵敏度为主",
    },
    "dota2": {
        "name": "Dota 2",
        "category": "MOBA",
        "yaw": 0.022,
        "bias": 0.0,
        "note": "MOBA 类游戏，高灵敏度为主",
    },
    "sc2": {
        "name": "星际争霸2",
        "category": "RTS",
        "yaw": 0.022,
        "bias": 0.0,
        "note": "RTS 类游戏，频繁快速移动",
    },
    "general": {
        "name": "通用/办公",
        "category": "通用",
        "yaw": 0.022,
        "bias": 0.0,
        "note": "通用参考值",
    },
}

# Backward-compatible alias for the API
GAME_GENRE_BIAS = GAMES


